name = "addtocloud-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./out"

# Node.js compatibility for Cloudflare
[build]
command = "npm run build:cloudflare"
publish = "./out"

[env.production]
name = "addtocloud-production"
compatibility_flags = ["nodejs_compat"]

[env.staging]  
name = "addtocloud-staging"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "addtocloud-dev"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "addtocloud-production"

[env.staging]  
name = "addtocloud-staging"

[env.development]
name = "addtocloud-dev"

# Environment variables for build
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://api.addtocloud.tech"
NEXT_PUBLIC_APP_URL = "https://addtocloud.tech"
NEXT_PUBLIC_ENVIRONMENT = "production"

# Development environment variables
[env.development.vars]
NODE_ENV = "development"
NEXT_PUBLIC_API_URL = "http://localhost:8080"
NEXT_PUBLIC_APP_URL = "http://localhost:3000"
NEXT_PUBLIC_ENVIRONMENT = "development"

# Staging environment variables
[env.staging.vars]
NODE_ENV = "staging"
NEXT_PUBLIC_API_URL = "https://staging-api.addtocloud.tech"
NEXT_PUBLIC_APP_URL = "https://staging.addtocloud.tech"
NEXT_PUBLIC_ENVIRONMENT = "staging"

# Custom domains
[[env.production.routes]]
pattern = "addtocloud.tech"

[[env.production.routes]]
pattern = "www.addtocloud.tech"

# Pages configuration
[pages_build_output_dir]
dir = "./out"

# KV storage (for caching)
[[kv_namespaces]]
binding = "CACHE"
id = "${CLOUDFLARE_KV_NAMESPACE_ID}"
preview_id = "${CLOUDFLARE_KV_PREVIEW_NAMESPACE_ID}"

# R2 storage (for assets)
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "addtocloud-assets"
preview_bucket_name = "addtocloud-assets-preview"

# D1 database (if needed for edge functions)
[[d1_databases]]
binding = "DB"
database_name = "addtocloud-edge"
database_id = "${CLOUDFLARE_D1_DATABASE_ID}"

# Analytics
[analytics_engine_datasets]
binding = "ANALYTICS"

# Custom headers
[[rules]]
rule = "*"
headers = { "X-Frame-Options" = "DENY", "X-Content-Type-Options" = "nosniff" }

# Cache configuration
[cache]
browser_ttl = 31536000  # 1 year
edge_ttl = 86400        # 1 day

# Security headers
[security]
tls = "strict"
always_use_https = true

# Performance optimizations
[minify]
javascript = true
css = true
html = true

# Compression
[compression]
enabled = true
algorithms = ["gzip", "brotli"]
