apiVersion: v1
kind: Service
metadata:
  name: addtocloud-api-public
  namespace: addtocloud-prod
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  labels:
    app: addtocloud-api-public
spec:
  type: LoadBalancer
  selector:
    app: addtocloud-api-frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
