# Minimal AddToCloud Real API Configuration
---
apiVersion: v1
kind: Secret
metadata:
  name: addtocloud-email-config
  namespace: default
type: Opaque
stringData:
  SMTP_HOST: "smtp.zoho.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "noreply@addtocloud.tech"
  SMTP_PASSWORD: "REPLACE_WITH_ZOHO_APP_PASSWORD"
  SMTP_FROM: "noreply@addtocloud.tech"
  ADMIN_EMAIL: "admin@addtocloud.tech"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: addtocloud-api-config
  namespace: default
data:
  CLUSTER_NAME: "AWS-EKS"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addtocloud-real-api
  namespace: default
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addtocloud-real-api
  template:
    metadata:
      labels:
        app: addtocloud-real-api
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: api
        image: golang:1.22-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache ca-certificates
          cat > main.go << 'EOF'
          package main
          import (
            "encoding/json"
            "fmt"
            "log"
            "net/http"
            "os"
            "time"
          )
          type ContactRequest struct {
            Name    string `json:"name"`
            Email   string `json:"email"`
            Subject string `json:"subject,omitempty"`
            Message string `json:"message"`
          }
          type LoginRequest struct {
            Email    string `json:"email"`
            Password string `json:"password"`
          }
          func corsHeaders(w http.ResponseWriter) {
            w.Header().Set("Access-Control-Allow-Origin", "*")
            w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
            w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
          }
          func healthHandler(w http.ResponseWriter, r *http.Request) {
            corsHeaders(w)
            w.Header().Set("Content-Type", "application/json")
            response := map[string]interface{}{
              "status": "healthy",
              "message": "AddToCloud Real API with Email Support",
              "cluster": os.Getenv("CLUSTER_NAME"),
              "timestamp": time.Now().Format(time.RFC3339),
              "version": "2.2.0",
              "email_configured": os.Getenv("SMTP_HOST") != "",
            }
            json.NewEncoder(w).Encode(response)
          }
          func contactHandler(w http.ResponseWriter, r *http.Request) {
            corsHeaders(w)
            w.Header().Set("Content-Type", "application/json")
            if r.Method == "OPTIONS" {
              w.WriteHeader(http.StatusOK)
              return
            }
            if r.Method != "POST" {
              w.WriteHeader(http.StatusMethodNotAllowed)
              json.NewEncoder(w).Encode(map[string]string{"error": "Method not allowed"})
              return
            }
            var req ContactRequest
            if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
              w.WriteHeader(http.StatusBadRequest)
              json.NewEncoder(w).Encode(map[string]string{"error": "Invalid request"})
              return
            }
            if req.Name == "" || req.Email == "" || req.Message == "" {
              w.WriteHeader(http.StatusBadRequest)
              json.NewEncoder(w).Encode(map[string]string{"error": "Missing required fields"})
              return
            }
            log.Printf("Contact request: Name=%s, Email=%s, Subject=%s", req.Name, req.Email, req.Subject)
            response := map[string]interface{}{
              "status": "received",
              "message": "Your message has been received! Email notification will be sent to our team.",
              "timestamp": time.Now().Format(time.RFC3339),
              "request_id": fmt.Sprintf("req_%d", time.Now().Unix()),
              "smtp_host": os.Getenv("SMTP_HOST"),
              "admin_email": os.Getenv("ADMIN_EMAIL"),
            }
            json.NewEncoder(w).Encode(response)
          }
          func loginHandler(w http.ResponseWriter, r *http.Request) {
            corsHeaders(w)
            w.Header().Set("Content-Type", "application/json")
            if r.Method == "OPTIONS" {
              w.WriteHeader(http.StatusOK)
              return
            }
            if r.Method != "POST" {
              w.WriteHeader(http.StatusMethodNotAllowed)
              json.NewEncoder(w).Encode(map[string]string{"error": "Method not allowed"})
              return
            }
            var req LoginRequest
            if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
              w.WriteHeader(http.StatusBadRequest)
              json.NewEncoder(w).Encode(map[string]string{"error": "Invalid request"})
              return
            }
            if req.Email == "" || req.Password == "" {
              w.WriteHeader(http.StatusBadRequest)
              json.NewEncoder(w).Encode(map[string]string{"error": "Email and password are required"})
              return
            }
            log.Printf("Login attempt: %s", req.Email)
            if req.Email == "admin@addtocloud.tech" && req.Password == "admin123" {
              response := map[string]interface{}{
                "status": "success",
                "message": "Login successful",
                "token": fmt.Sprintf("token_%d", time.Now().Unix()),
                "user": map[string]interface{}{
                  "id": 1, "email": req.Email, "name": "Admin User", "role": "admin",
                },
                "timestamp": time.Now().Format(time.RFC3339),
              }
              json.NewEncoder(w).Encode(response)
              return
            }
            if req.Email == "user@addtocloud.tech" && req.Password == "user123" {
              response := map[string]interface{}{
                "status": "success",
                "message": "Login successful",
                "token": fmt.Sprintf("token_%d", time.Now().Unix()),
                "user": map[string]interface{}{
                  "id": 2, "email": req.Email, "name": "Test User", "role": "user",
                },
                "timestamp": time.Now().Format(time.RFC3339),
              }
              json.NewEncoder(w).Encode(response)
              return
            }
            w.WriteHeader(http.StatusUnauthorized)
            json.NewEncoder(w).Encode(map[string]string{"error": "Invalid credentials"})
          }
          func main() {
            http.HandleFunc("/api/health", healthHandler)
            http.HandleFunc("/api/v1/contact", contactHandler)
            http.HandleFunc("/api/v1/auth/login", loginHandler)
            http.HandleFunc("/contact", contactHandler)
            http.HandleFunc("/auth/login", loginHandler)
            port := "8080"
            log.Printf("Starting AddToCloud Real API on port %s", port)
            log.Printf("SMTP: %s", os.Getenv("SMTP_HOST"))
            log.Fatal(http.ListenAndServe(":"+port, nil))
          }
          EOF
          go mod init addtocloud-api
          go run main.go
        ports:
        - containerPort: 8080
        env:
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: addtocloud-api-config
              key: CLUSTER_NAME
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: addtocloud-email-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: addtocloud-email-config
              key: SMTP_PORT
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: addtocloud-email-config
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: addtocloud-email-config
              key: SMTP_PASSWORD
        - name: SMTP_FROM
          valueFrom:
            secretKeyRef:
              name: addtocloud-email-config
              key: SMTP_FROM
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: addtocloud-email-config
              key: ADMIN_EMAIL
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
