version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: addtocloud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: addtocloud_prod
      POSTGRES_USER: addtocloud
      POSTGRES_PASSWORD: addtocloud_secure_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - addtocloud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U addtocloud -d addtocloud_prod"]
      interval: 30s
      timeout: 10s
      retries: 5

  # PostgreSQL Admin (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: addtocloud-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@addtocloud.tech
      PGADMIN_DEFAULT_PASSWORD: addtocloud_admin_2024
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - addtocloud-network
    depends_on:
      - postgres

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: addtocloud-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: addtocloud
      MONGO_INITDB_ROOT_PASSWORD: addtocloud_mongo_2024
      MONGO_INITDB_DATABASE: addtocloud_logs
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./database/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - addtocloud-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MongoDB Admin (Mongo Express)
  mongo-express:
    image: mongo-express:latest
    container_name: addtocloud-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: addtocloud
      ME_CONFIG_MONGODB_ADMINPASSWORD: addtocloud_mongo_2024
      ME_CONFIG_MONGODB_URL: mongodb://addtocloud:addtocloud_mongo_2024@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: addtocloud_admin_2024
    ports:
      - "8081:8081"
    networks:
      - addtocloud-network
    depends_on:
      - mongodb

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: addtocloud-redis
    restart: unless-stopped
    command: redis-server --requirepass addtocloud_redis_2024 --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - addtocloud-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Admin (RedisInsight)
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: addtocloud-redisinsight
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db
    networks:
      - addtocloud-network
    depends_on:
      - redis

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local
  redisinsight_data:
    driver: local

networks:
  addtocloud-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
