apiVersion: apps/v1
kind: Deployment
metadata:
  name: addtocloud-simple-api
  namespace: default
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addtocloud-simple-api
  template:
    metadata:
      labels:
        app: addtocloud-simple-api
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: api
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: api-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: api-html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "8Mi"
            cpu: "5m"
          limits:
            memory: "16Mi"
            cpu: "10m"
      volumes:
      - name: api-config
        configMap:
          name: api-nginx-config
      - name: api-html
        configMap:
          name: api-html-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-nginx-config
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        server {
            listen 80;
            server_name _;
            
            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Content-Type" always;
            
            location /api/health {
                add_header Content-Type application/json;
                return 200 '{"status":"healthy","message":"AddToCloud API is running","cluster":"AWS-EKS","timestamp":"2025-08-29T16:45:00Z","version":"1.0.0"}';
            }
            
            location /api/v1/contact {
                if ($request_method = OPTIONS) {
                    return 204;
                }
                if ($request_method != POST) {
                    add_header Content-Type application/json;
                    return 405 '{"error":"Method not allowed"}';
                }
                add_header Content-Type application/json;
                return 200 '{"status":"received","message":"Your message has been received successfully","timestamp":"2025-08-29T16:45:00Z"}';
            }
            
            location /api/v1/auth/login {
                if ($request_method = OPTIONS) {
                    return 204;
                }
                if ($request_method != POST) {
                    add_header Content-Type application/json;
                    return 405 '{"error":"Method not allowed"}';
                }
                add_header Content-Type application/json;
                return 200 '{"status":"success","message":"Login successful","token":"demo-jwt-token-123","user":{"email":"admin@addtocloud.tech","name":"Admin User","role":"admin"},"timestamp":"2025-08-29T16:45:00Z"}';
            }
            
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-html-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>AddToCloud API</title>
    </head>
    <body>
        <h1>AddToCloud API</h1>
        <p>API is running on AWS EKS</p>
        <ul>
            <li><a href="/api/health">/api/health</a> - Health check</li>
            <li>/api/v1/contact - Contact form (POST)</li>
            <li>/api/v1/auth/login - Login (POST)</li>
        </ul>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: addtocloud-simple-api
  namespace: default
spec:
  selector:
    app: addtocloud-simple-api
  ports:
  - name: http
    port: 8080
    targetPort: 80
  type: ClusterIP
