# Cloudflare Pages configuration for Next.js app
name = "addtocloud"
compatibility_date = "2024-01-01"

# Pages-specific configuration
pages_build_output_dir = "frontend/out"

# Only production and preview environments are supported by Pages
[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]