name = "addtocloud-frontend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration for Next.js app in frontend folder
pages_build_output_dir = "frontend/out"

# Build configuration - use simple approach
[build]
command = "cd frontend && npm install && npm run build"
cwd = "."

# Environment variables for production
[env.production]
name = "addtocloud-production"
compatibility_flags = ["nodejs_compat"]

[env.staging]  
name = "addtocloud-staging"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "addtocloud-dev"
compatibility_flags = ["nodejs_compat"]