# Persistent Storage Configuration for Multi-Cloud Database Deployment
# AWS EFS, GCP Filestore, Azure Files integration for Kubernetes clusters

apiVersion: v1
kind: ConfigMap
metadata:
  name: persistent-storage-config
  namespace: database
data:
  storage-strategy.yaml: |
    # AWS EFS StorageClass for EKS
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: efs-sc
    provisioner: efs.csi.aws.com
    parameters:
      provisioningMode: efs-ap
      fileSystemId: fs-0123456789abcdef0
      directoryPerms: "0755"
      gidRangeStart: "1000"
      gidRangeEnd: "2000"
      basePath: "/addtocloud"
    mountOptions:
    - tls
    - accesspoint=fsap-01234567
    volumeBindingMode: Immediate
    
    ---
    # GCP Filestore StorageClass for GKE
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: filestore-sc
    provisioner: filestore.csi.storage.gke.io
    parameters:
      tier: standard
      network: projects/PROJECT_ID/global/networks/default
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    
    ---
    # Azure Files StorageClass for AKS
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: azurefile-sc
    provisioner: file.csi.azure.com
    parameters:
      skuName: Premium_LRS
      protocol: nfs
      shareAccessTier: Premium
    mountOptions:
    - dir_mode=0755
    - file_mode=0755
    - uid=1001
    - gid=1001
    - mfsymlinks
    - cache=strict
    - nosharesock
    volumeBindingMode: Immediate
    allowVolumeExpansion: true

---
# PostgreSQL PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc
  namespace: database
  labels:
    app: postgresql
    component: primary
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc # Use appropriate SC for each cloud
  resources:
    requests:
      storage: 100Gi

---
# MongoDB PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  namespace: database
  labels:
    app: mongodb
    component: primary
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 200Gi

---
# Redis PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: database
  labels:
    app: redis
    component: master
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi

---
# Logs PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: monitoring
  labels:
    app: fluentd
    component: logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 500Gi

---
# Backup PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: database
  labels:
    app: backup
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Ti
