services:
  - type: web
    name: addtocloud-api
    runtime: go
    buildCommand: go build -o main cmd/main.go
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
      - key: DB_HOST
        value: ""
      - key: DB_USER
        value: ""
      - key: POSTGRES_PASSWORD
        value: ""
      - key: DB_NAME
        value: ""
      - key: DB_PORT
        value: ""
      - key: DB_SSLMODE
        value: "disable"
