global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'multi-cloud'
    environment: 'production'

rule_files:
  - "rules/*.yml"
  - "alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Multi-Cloud Federation Configuration
remote_read:
  - url: "http://prometheus-aws.monitoring.svc.cluster.local:9090/api/v1/read"
    remote_timeout: 30s
    read_recent: true
    
  - url: "http://prometheus-azure.monitoring.svc.cluster.local:9090/api/v1/read"
    remote_timeout: 30s
    read_recent: true
    
  - url: "http://prometheus-gcp.monitoring.svc.cluster.local:9090/api/v1/read"
    remote_timeout: 30s
    read_recent: true

remote_write:
  - url: "http://prometheus-federation.monitoring.svc.cluster.local:9090/api/v1/write"
    remote_timeout: 30s

scrape_configs:
  # AddToCloud Application Metrics
  - job_name: 'addtocloud-backend'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['addtocloud-prod']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: addtocloud-backend
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  - job_name: 'addtocloud-frontend'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['addtocloud-prod']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: addtocloud-frontend

  # Istio Service Mesh Metrics
  - job_name: 'istio-mesh'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: ['istio-system']
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: istio-telemetry;prometheus

  # Database Metrics
  - job_name: 'postgresql'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['database']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: postgresql

  - job_name: 'redis'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['database']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: redis

  - job_name: 'mongodb'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['database']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: mongodb

  # Kubernetes Cluster Metrics
  - job_name: 'kubernetes-nodes'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

  # Cloud Provider Specific Metrics
  - job_name: 'aws-cloudwatch'
    ec2_sd_configs:
      - region: us-west-2
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        action: replace
        target_label: instance_name

  - job_name: 'azure-monitor'
    static_configs:
      - targets: ['azure-exporter:9090']
        labels:
          cloud_provider: 'azure'

  - job_name: 'gcp-monitoring'
    static_configs:
      - targets: ['stackdriver-exporter:9255']
        labels:
          cloud_provider: 'gcp'
