# Frontend Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addtocloud-frontend
  namespace: addtocloud
  labels:
    app: addtocloud-frontend
    component: frontend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: addtocloud-frontend
  template:
    metadata:
      labels:
        app: addtocloud-frontend
        component: frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: addtocloud/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.addtocloud.tech"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: addtocloud-frontend
  namespace: addtocloud
  labels:
    app: addtocloud-frontend
spec:
  selector:
    app: addtocloud-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
