apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: addtocloud

commonLabels:
  environment: production
  stage: prod

configMapGenerator:
- name: addtocloud-config
  literals:
  - environment=production
  - log-level=warn
  - api-url=https://api.addtocloud.tech
  - app-url=https://addtocloud.tech

secretGenerator:
- name: addtocloud-secrets
  literals:
  - database-url=postgresql://postgres:production_password@postgres:5432/addtocloud_prod
  - redis-url=redis://:production_password@redis:6379/2
  - postgres-database=addtocloud_prod
  - postgres-username=postgres
  - postgres-password=production_password
  - redis-password=production_password

images:
- name: addtocloud/backend
  newTag: latest
- name: addtocloud/frontend
  newTag: latest
