apiVersion: v1
kind: ConfigMap
metadata:
  name: addtocloud-config
  namespace: addtocloud
data:
  # Database Configuration
  DATABASE_NAME: "addtocloud_dev"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # MongoDB Configuration
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "addtocloud_dev"
  
  # Application Configuration
  ENVIRONMENT: "development"
  LOG_LEVEL: "debug"
  API_BASE_URL: "http://localhost:3001"
  FRONTEND_URL: "http://localhost:3000"
  
  # Feature Flags
  ENABLE_MONITORING: "true"
  ENABLE_CACHING: "true"
  ENABLE_RATE_LIMITING: "false"
  
  # External Services
  CLOUDFLARE_ZONE_ID: ""
