# AWS EKS Cluster Configuration
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: addtocloud-eks-primary
  region: us-east-1
  version: "1.27"

# IAM configuration
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaling: true

# VPC configuration
vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

# Node groups
nodeGroups:
  # Primary node group for system workloads
  - name: system-nodes
    instanceType: c5.large
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    volumeSize: 50
    volumeType: gp3
    ssh:
      enableSsm: true
    labels:
      node-type: system
    taints:
      - key: node-type
        value: system
        effect: NoSchedule

  # Application node group
  - name: app-nodes
    instanceType: m5.large
    desiredCapacity: 5
    minSize: 3
    maxSize: 10
    volumeSize: 100
    volumeType: gp3
    ssh:
      enableSsm: true
    labels:
      node-type: application
    tags:
      Environment: production
      Project: addtocloud

# Managed add-ons
addons:
- name: vpc-cni
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  version: latest

# CloudWatch logging
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
