apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - databases.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - services.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: addtocloud
  app.kubernetes.io/instance: addtocloud
  app.kubernetes.io/component: platform
  app.kubernetes.io/part-of: addtocloud-platform
  app.kubernetes.io/managed-by: kustomize
