apiVersion: v1
kind: ServiceAccount
metadata:
  name: addtocloud-backend
  labels:
    component: backend
    tier: api
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: addtocloud-frontend
  labels:
    component: frontend
    tier: web
automountServiceAccountToken: false
