# Kubernetes Secrets for Database Passwords
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: addtocloud
type: Opaque
data:
  postgres-password: YWRkdG9jbG91ZF9wb3N0Z3Jlc19wYXNzd29yZA== # base64: addtocloud_postgres_password
  mongodb-password: YWRkdG9jbG91ZF9tb25nb2RiX3Bhc3N3b3Jk # base64: addtocloud_mongodb_password
  redis-password: YWRkdG9jbG91ZF9yZWRpc19wYXNzd29yZA== # base64: addtocloud_redis_password

---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: addtocloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: addtocloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: addtocloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
