apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: addtocloud-prod

resources:
  - ../../../base

commonLabels:
  environment: production
  cloud: aws
  cluster: aws-production

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
    target:
      kind: Deployment
      name: addtocloud-backend

  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
    target:
      kind: Deployment
      name: addtocloud-backend

configMapGenerator:
  - name: aws-config
    literals:
      - AWS_REGION=us-west-2
      - CLOUD_PROVIDER=aws
      - CLUSTER_NAME=addtocloud-aws-production
      - STORAGE_CLASS=gp3

images:
  - name: addtocloud-backend
    newTag: aws-production
  - name: addtocloud-frontend
    newTag: aws-production
