# GCP-specific patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addtocloud-frontend
  namespace: addtocloud
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-nodepool: frontend-pool
      tolerations:
      - key: "cloud.google.com/gke-preemptible"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addtocloud-backend
  namespace: addtocloud
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        cloud.google.com/gke-nodepool: backend-pool
      tolerations:
      - key: "cloud.google.com/gke-preemptible"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: addtocloud
spec:
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ssd
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: addtocloud
spec:
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ssd
      resources:
        requests:
          storage: 20Gi
---
# GCP Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: addtocloud-frontend-lb
  namespace: addtocloud
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "addtocloud-backend-config"}'
spec:
  type: LoadBalancer
  selector:
    app: addtocloud-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: addtocloud-backend-config
  namespace: addtocloud
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 3000
  connectionDraining:
    drainingTimeoutSec: 60
