apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml

namePrefix: dev-
namespace: addtocloud-dev

commonLabels:
  environment: development
  version: v1.0.0
