apiVersion: v2
name: addtocloud-platform
description: AddToCloud Enterprise Platform Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  
  - name: mongodb
    version: 13.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled

  - name: prometheus
    version: 15.18.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled

  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled

keywords:
  - addtocloud
  - enterprise
  - cloud
  - platform
  - microservices
  - multi-cloud

maintainers:
  - name: AddToCloud Team
    email: admin@addtocloud.tech
