apiVersion: apps/v1
kind: Deployment
metadata:
  name: credential-service
  namespace: addtocloud
  labels:
    app: credential-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credential-service
  template:
    metadata:
      labels:
        app: credential-service
        version: v1
    spec:
      containers:
      - name: credential-service
        image: ghcr.io/gokulupadhyayguragain/addtocloud/credential-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: EMAIL_SMTP_HOST
          value: "smtp.gmail.com"
        - name: EMAIL_SMTP_PORT
          value: "587"
        - name: EMAIL_FROM
          value: "noreply@addtocloud.tech"
        - name: EMAIL_TO
          value: "gokul@addtocloud.tech"
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: password
        - name: API_PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: credential-service
  namespace: addtocloud
  labels:
    app: credential-service
spec:
  selector:
    app: credential-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: addtocloud
type: Opaque
data:
  # Base64 encoded email app password
  # Replace with actual app password: echo -n "your_email_app_password" | base64
  password: eW91cl9lbWFpbF9hcHBfcGFzc3dvcmQ=
